apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-crud
  template:
    metadata:
      labels:
        app: fastapi-crud
    spec:
      containers:
      - name: fastapi-crud
        image: vipunsanjana/fastapi-crud:one
        ports:
        - containerPort: 80
